//
// Concatenates reset.css + animation.css + theme.css + utilities.css (both generated by
// scripts/build.js) into a single dist file. Run scripts/build.js first.
//

import { readFileSync, writeFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { minify } from "csso";

const ROOT = process.cwd();
const FILES = ["reset.css", "theme.css", "utilities.css", "animation.css", "helpers.css", "form.css"];
const OUTPUT = join(ROOT, "low.css");

const parts = FILES.map(file => {
    const content = readFileSync(join(ROOT, file), "utf8");
    return `/* ---- ${file} ---- */\n${content}`;
});

const result = minify(parts.join("\n"), {
    sourceMap: false,
});

writeFileSync(OUTPUT, result.css);

console.log(`✓ built ${relative(ROOT, OUTPUT)} (${statSync(OUTPUT).size} bytes)`);
