name: Publish
on:
  push:
    tags: ['*']
## https://github.com/softprops/action-gh-release#permissions 
permissions:
  contents: write
jobs:
  publish:
    if: ${{ github.repository == 'jmjuanes/lowcss' }}
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn run build
      - run: yarn publish
